version: '3.8'

services:
  postgres:
    image: postgres
    container_name: postgres_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${DB_PORT}:5432"
    restart: always

  nginx:
    image: nginx
    container_name: nginx_server
    ports:
      - "80:80"
    restart: always