import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";

import { Header } from "./components/header/Header";
import { Hero } from "./components/Hero/Hero";
import { FeatureList } from "./components/FeatureList/FeatureList";
import { Contatos } from "./components/Contatos/Contatos";
import "./globals.css";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Header></Header>
        <Hero></Hero>
        <FeatureList></FeatureList>
        <Contatos></Contatos>
        {children}
      </body>
    </html>
  );
}
